spring:
  datasource:
    platform: ${DATABASE_PLATFORM}
    driverClassName: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: false

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

  application:
    name: resource-service

  cloud:
    config:
      enabled: false

aws:
  credentials:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
  endpoint-config:
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}

server:
  port: 8088

eureka:
  client:
    client:
      enabled: true
      fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

resilience4j.circuitbreaker:
  instances:
    storageServiceCallCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10
      failureRateThreshold: 50

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always