spring:
  datasource:
    platform: ${DATABASE_PLATFORM}
    driverClassName: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

aws:
  credentials:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
  endpoint-config:
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}

server:
  port: 8080